# Generated by Django 5.2 on 2025-04-10 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_tagcategory_tag_tag_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='SubjectCategory',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='category',
            new_name='subject_category',
        ),
    ]
