# Generated by Django 5.2 on 2025-04-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_rename_category_subjectcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starenrollment',
            name='question',
        ),
        migrations.RemoveField(
            model_name='tagenrollment',
            name='question',
        ),
        migrations.RemoveField(
            model_name='starenrollment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tagenrollment',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='StarEnrollment',
        ),
        migrations.DeleteModel(
            name='TagEnrollment',
        ),
    ]
