# Generated by Django 5.2 on 2025-04-13 15:34

import django.db.models.deletion
import qna.models.question
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_remove_starenrollment_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=qna.models.question.question_upload)),
                ('content', models.TextField(blank=True)),
                ('vector', models.JSONField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='qna.subjectcategory')),
            ],
        ),
        migrations.CreateModel(
            name='StarEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='qna.question')),
            ],
        ),
        migrations.CreateModel(
            name='TagEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='qna.question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qna.tag')),
            ],
        ),
    ]
