# Generated by Django 5.2 on 2025-04-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_question_starenrollment_tagenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
