# Generated by Django 5.2 on 2025-05-15 03:04

import qna.models.solution
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0007_studentsolution_likeenrollment_teachersolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsolution',
            name='image',
            field=models.ImageField(upload_to=qna.models.solution.student_solution_upload),
        ),
        migrations.AlterField(
            model_name='teachersolution',
            name='image',
            field=models.ImageField(upload_to=qna.models.solution.teacher_solution_upload),
        ),
    ]
