# Generated by Django 5.2 on 2025-06-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0008_alter_studentsolution_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='questions', to='qna.tag'),
        ),
        migrations.DeleteModel(
            name='TagEnrollment',
        ),
    ]
