# Generated by Django 5.2 on 2025-05-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mastery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.IntegerField(default=100),
        ),
    ]
